title: Fisika Komputasi & Teoritik (FKT)
email: fkt@um.ac.id
description: "Kelompok Bidang Keahlian Fisika Komputasi dan Teoritik, Universitas Negeri Malang"
url: "https://fkt-fisika-um.github.io"
baseurl: ""

# Tema Minimal Mistakes
theme: minima

# Repository (opsional)
repository: fkt-fisika-um/fkt-fisika-um.github.io

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugin
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigasi
navigation:
  - title: Beranda
    url: /
  - title: Tentang
    url: /tentang/
  - title: Anggota
    url: /anggota/
  - title: Proyek
    url: /proyek/
  - title: Publikasi
    url: /publikasi/
  - title: Blog
    url: /blog/